#this is used in the unraid ui with the community app compose manager to setup basic settings for portainer to initially pull all containers
version: '3'

services:
  portainer-init:
    image: portainer/portainer-ce:latest
    container_name: portainer-init
    restart: unless-stopped
    ports:
      - "9001:9000"
    networks:
      - network-init
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/user/appdata/portainer:/data

networks:
  network-init:
    name: network-init
    driver: bridge  # Use bridge for temporary network