services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    networks:
      vlan-downloads:
        ipv4_address: 192.168.60.60
    ports:
      - "8080:8080" #webui
      - "1637:1637"  # VPN torrenting port
      - "1637:1637/udp"  # VPN torrenting port UDP
    volumes:
      - /mnt/user/appdata/qbittorrent:/config
      - /mnt/user/plexdownloads:/downloads
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - DOMAIN=${DOMAIN}
      - TORRENTING_PORT=1637
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbit.rule=Host(`downloads.${DOMAIN}`)"
      - "traefik.http.routers.qbit.entrypoints=websecure"
      - "traefik.http.routers.qbit.tls=true"
      - "traefik.http.routers.qbit.tls.certresolver=dns-cloudflare"
      - "traefik.http.services.qbit.loadbalancer.server.port=8080"
      #- "traefik.http.routers.qbit.middlewares=ipwhitelist"
      - "traefik.http.services.qbit.loadbalancer.passHostHeader=true"
      - "traefik.http.services.qbit.loadbalancer.server.scheme=http"