networks:
  vlan-private:
    external: true
    name: br0
  vlan-downloads:
    external: true

services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    privileged: true
    networks:
      vlan-private:
        ipv4_address: 192.168.1.10
    ports:
      - "1900:1900/udp"    # DLNA discovery
      - "3005:3005"        # Plex Companion (Mobile apps)
      - "5353:5353/udp"    # Bonjour/Avahi discovery
      - "8324:8324"        # Roku via UPNP
      - "32400:32400"      # Primary communication/Web interface
      - "32410:32410/udp"  # GDM network discovery
      - "32412:32412/udp"  # GDM network discovery
      - "32413:32413/udp"  # GDM network discovery
      - "32414:32414/udp"  # GDM network discovery
      - "32469:32469"      # DLNA media transfer
    devices:
      - /dev/dri:/dev/dri  # For Intel QuickSync/Graphics
    volumes:
      - /mnt/user/appdata/plex:/config
      - /mnt/user/plexmedia/movies:/movies
      - /mnt/user/plexmedia/tv:/tv
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      - DOMAIN=${DOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`plex.${DOMAIN}`)"
      - "traefik.http.routers.plex.entrypoints=websecure"
      - "traefik.http.routers.plex.tls=true"
      - "traefik.http.routers.plex.tls.certresolver=dns-cloudflare"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
      #- "traefik.http.routers.plex.middlewares=ipwhitelist"
      - "traefik.http.services.plex.loadbalancer.passHostHeader=true"
      - "traefik.http.services.plex.loadbalancer.server.scheme=http"

  prowlarr: #indexer
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    networks:
      vlan-downloads:
        ipv4_address: 192.168.60.61  
    ports:
      - "9696:9696"  # Prowlarr web interface
    volumes:
      - /mnt/user/appdata/prowlarr:/config
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - DOMAIN=${DOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`indexer.${DOMAIN}`)"
      - "traefik.http.routers.prowlarr.entrypoints=websecure"
      - "traefik.http.routers.prowlarr.tls=true"
      - "traefik.http.routers.prowlarr.tls.certresolver=dns-cloudflare"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
      #- "traefik.http.routers.prowlarr.middlewares=ipwhitelist"
      - "traefik.http.services.prowlarr.loadbalancer.passHostHeader=true"
      - "traefik.http.services.prowlarr.loadbalancer.server.scheme=http"

  sonarr: #tv
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    networks:
      vlan-downloads:
        ipv4_address: 192.168.60.62
    ports:
      - "8989:8989"  # Sonarr web interface
    volumes:
      - /mnt/user/appdata/sonarr:/config
      - /mnt/user/plexmedia/tv:/tv
      - /mnt/user/downloads/usenet:/downloads/usenet
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - DOMAIN=${DOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`tv.${DOMAIN}`)"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.routers.sonarr.tls.certresolver=dns-cloudflare"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      #- "traefik.http.routers.sonarr.middlewares=ipwhitelist"
      - "traefik.http.services.sonarr.loadbalancer.passHostHeader=true"
      - "traefik.http.services.sonarr.loadbalancer.server.scheme=http"

  radarr: #movies
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    networks:
      vlan-downloads:
        ipv4_address: 192.168.60.63
    ports:
      - "7878:7878"  # Radarr web interface
    volumes:
      - /mnt/user/appdata/radarr:/config
      - /mnt/user/plexmedia/movies:/movies
      - /mnt/user/downloads/usenet:/downloads/usenet
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - DOMAIN=${DOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`movies.${DOMAIN}`)"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.tls.certresolver=dns-cloudflare"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      #- "traefik.http.routers.radarr.middlewares=ipwhitelist"
      - "traefik.http.services.radarr.loadbalancer.passHostHeader=true"
      - "traefik.http.services.radarr.loadbalancer.server.scheme=http"

  bazarr: #subtitles
    image: linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    networks:
      vlan-downloads:
        ipv4_address: 192.168.60.64
    ports:
      - "6767:6767" #web interface
    volumes:
      - /mnt/user/appdata/bazarr:/config
      - /mnt/user/plexmedia/tv:/tv
      - /mnt/user/plexmedia/movies:/movies
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - DOMAIN=${DOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.rule=Host(`subtitles.${DOMAIN}`)"
      - "traefik.http.routers.bazarr.entrypoints=websecure"
      - "traefik.http.routers.bazarr.tls=true"
      - "traefik.http.routers.bazarr.tls.certresolver=dns-cloudflare"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"
      #- "traefik.http.routers.bazarr.middlewares=ipwhitelist"
      - "traefik.http.services.bazarr.loadbalancer.passHostHeader=true"
      - "traefik.http.services.bazarr.loadbalancer.server.scheme=http"
  
  overseerr: #requests
    image: sctx/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    networks:
      vlan-downloads:
        ipv4_address: 192.168.60.65
    ports:
      - "5055:5055" #web interface
    volumes:
      - /mnt/user/appdata/overseerr:/app/config
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - DOMAIN=${DOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.rule=Host(`request.${DOMAIN}`)"
      - "traefik.http.routers.overseerr.entrypoints=websecure"
      - "traefik.http.routers.overseerr.tls=true"
      - "traefik.http.routers.overseerr.tls.certresolver=dns-cloudflare"
      - "traefik.http.services.overseerr.loadbalancer.server.port=5055"
      #- "traefik.http.routers.overseerr.middlewares=ipwhitelist"
      - "traefik.http.services.overseerr.loadbalancer.passHostHeader=true"
      - "traefik.http.services.overseerr.loadbalancer.server.scheme=http"
  
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    networks:
      #vlan-private:
      #  ipv4_address: 192.168.1.66
      vlan-downloads:
        ipv4_address: 192.168.60.66
    ports:
      - 8080:8080
    volumes:
      - /mnt/user/appdata/sabnzbd:/config
      - /mnt/user/downloads/usenet:/downloads/usenet
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - DOMAIN=${DOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sabnzbd.rule=Host(`usenet.${DOMAIN}`)"
      - "traefik.http.routers.sabnzbd.entrypoints=websecure"
      - "traefik.http.routers.sabnzbd.tls=true"
      - "traefik.http.routers.sabnzbd.tls.certresolver=dns-cloudflare"
      - "traefik.http.services.sabnzbd.loadbalancer.server.port=8080"
      #- "traefik.http.routers.sabnzbd.middlewares=ipwhitelist"
      - "traefik.http.services.sabnzbd.loadbalancer.passHostHeader=true"
      - "traefik.http.services.sabnzbd.loadbalancer.server.scheme=http"
  