-- Home Assistant
CREATE USER IF NOT EXISTS ${HA_USER} WITH PASSWORD '${HA_PASS}';
CREATE DATABASE IF NOT EXISTS homeassistant;
GRANT ALL PRIVILEGES ON DATABASE homeassistant TO ${HA_USER};

-- kw
CREATE USER IF NOT EXISTS ${KW_USER} WITH PASSWORD '${KW_PASS}';
CREATE DATABASE IF NOT EXISTS kw;
GRANT ALL PRIVILEGES ON DATABASE kw TO ${KW_USER};

