version: '3'
services:
  traefik:
    image: traefik:3
    container_name: traefik
    networks:
      vlan-private:
        ipv4_address: 192.168.1.2
    ports:
      - "192.168.1.2:80:80"
      - "192.168.1.2:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "--api.insecure=true"  # This enables direct dashboard access
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
    restart: unless-stopped

networks:
  vlan-private:
    external: true
    name: br0