version: '3'

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    privileged: true
    networks:
      vlan-iot:
        ipv4_address: 192.168.40.40
    ports:
      - "8123:8123"
    volumes:
      - /mnt/user/appdata/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /dev/ttyACM0:/dev/ttyACM0 # Zooz 800 Z-Wave
    environment:
      - TZ=America/New_York
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=vlan-iot"  # Tell Traefik to use IoT network
      - "traefik.http.routers.hass.rule=Host(`ha.jamespate.net`)"
      - "traefik.http.routers.hass.tls=true"
    restart: unless-stopped

networks:
  vlan-iot:
    external: true
