version: '3'

networks:
  downloads_net:
    driver: macvlan
    driver_opts:
      parent: eth0.5
    ipam:
      config:
        - subnet: 192.168.5.0/24
          gateway: 192.168.5.1
  private_net:
    external: true

services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    networks:
      - private_net
      - downloads_net
    volumes:
      - ../config/plex:/config
      - /mnt/user/media:/data
    environment:
      - TZ=${TZ}
      - PUID=1000
      - PGID=100
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`plex.${DOMAIN}`)"
      - "traefik.http.routers.plex.tls=true"

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - downloads_net
    volumes:
      - ../config/sonarr:/config
      - /mnt/user/media/tv:/tv
      - /mnt/user/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=100
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN}`)"
      - "traefik.http.routers.sonarr.tls=true"

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    networks:
      - downloads_net
    volumes:
      - ../config/radarr:/config
      - /mnt/user/media/movies:/movies
      - /mnt/user/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=100
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN}`)"
      - "traefik.http.routers.radarr.tls=true"

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    networks:
      - downloads_net
    volumes:
      - ../config/prowlarr:/config
    environment:
      - PUID=1000
      - PGID=100
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.${DOMAIN}`)"
      - "traefik.http.routers.prowlarr.tls=true"

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    networks:
      - downloads_net
    volumes:
      - ../config/qbittorrent:/config
      - /mnt/user/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=100
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbit.rule=Host(`qbit.${DOMAIN}`)"
      - "traefik.http.routers.qbit.tls=true"
