version: '3'

env_file:
  - /boot/custom/.env

services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    depends_on:
      - traefik
    restart: unless-stopped
    privileged: true
    networks:
      vlan-private:
        ipv4_address: 192.168.1.10
    ports:
      - "1900:1900/udp"    # DLNA discovery
      - "3005:3005"        # Plex Companion (Mobile apps)
      - "5353:5353/udp"    # Bonjour/Avahi discovery
      - "8324:8324"        # Roku via UPNP
      - "32400:32400"      # Primary communication/Web interface
      - "32410:32410/udp"  # GDM network discovery
      - "32412:32412/udp"  # GDM network discovery
      - "32413:32413/udp"  # GDM network discovery
      - "32414:32414/udp"  # GDM network discovery
      - "32469:32469"      # DLNA media transfer
    devices:
      - /dev/dri:/dev/dri  # For Intel QuickSync/Graphics
    volumes:
      - /mnt/user/appdata/plex:/config
      - /mnt/user/plexmedia/movies:/movies
      - /mnt/user/plexmedia/tv:/tv
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_PREFERENCE_1="FriendlyName=pateplex"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=vlan-private"
      - "traefik.http.routers.plex.rule=Host(`plex.${DOMAIN}`)"
      - "traefik.http.routers.plex.tls=true"
      - "traefik.http.routers.plex.tls.certresolver=letsencrypt"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
  
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    depends_on:
      - traefik
    restart: unless-stopped
    networks:
      vlan-downloads:
        ipv4_address: 192.168.60.60
    ports:
      - "8080:8080" #webui
      - "6881:6881"  # Incoming connections
      - "6881:6881/udp"  # DHT
    volumes:
      - /mnt/user/appdata/qbittorrent:/config
      - /mnt/user/plexdownloads:/downloads
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=vlan-downloads"  # Tell Traefik which network to use
      - "traefik.http.routers.qbit.rule=Host(`downloads.${DOMAIN}`)"
      - "traefik.http.routers.qbit.tls=true"
      - "traefik.http.routers.qbit.tls.certresolver=letsencrypt"
      - "traefik.http.services.qbit.loadbalancer.server.port=8080"  # Specify the web UI port

  prowlarr: #indexer
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    depends_on:
      - traefik
      - qbittorrent
    restart: unless-stopped
    networks:
      vlan-downloads:
        ipv4_address: 192.168.60.61  
    ports:
      - "9696:9696"  # Prowlarr web interface
    volumes:
      - /mnt/user/appdata/prowlarr:/config
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=vlan-downloads"  # Use private network for web access
      - "traefik.http.routers.prowlarr.rule=Host(`indexer.${DOMAIN}`)"
      - "traefik.http.routers.prowlarr.tls=true"
      - "traefik.http.routers.prowlarr.tls.certresolver=letsencrypt"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
  
  sonarr: #tv
    image: linuxserver/sonarr:latest
    container_name: sonarr
    depends_on:
      - traefik
      - qbittorrent
      - prowlarr
    restart: unless-stopped
    networks:
      vlan-downloads:
        ipv4_address: 192.168.60.62
    ports:
      - "8989:8989"  # Sonarr web interface
    volumes:
      - /mnt/user/appdata/sonarr:/config
      - /mnt/user/plexmedia/tv:/tv
      - /mnt/user/plexdownloads:/downloads
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=vlan-downloads"
      - "traefik.http.routers.sonarr.rule=Host(`tv.${DOMAIN}`)"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.routers.sonarr.tls.certresolver=letsencrypt"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"

  radarr: #movies
    image: linuxserver/radarr:latest
    container_name: radarr
    depends_on:
      - traefik
      - qbittorrent
      - prowlarr
    restart: unless-stopped
    networks:
      vlan-downloads:
        ipv4_address: 192.168.60.63
    ports:
      - "7878:7878"  # Radarr web interface
    volumes:
      - /mnt/user/appdata/radarr:/config
      - /mnt/user/plexmedia/movies:/movies
      - /mnt/user/plexdownloads:/downloads
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=vlan-downloads"
      - "traefik.http.routers.radarr.rule=Host(`movies.${DOMAIN}`)"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.tls.certresolver=letsencrypt"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"

  bazarr: #subtitles
    image: linuxserver/bazarr:latest
    container_name: bazarr
    depends_on:
      - traefik
      - sonarr
      - radarr
    restart: unless-stopped
    networks:
      vlan-downloads:
        ipv4_address: 192.168.60.64
    ports:
      - "32400:32400" #web interface
    volumes:
      - /mnt/user/appdata/bazarr:/config
      - /mnt/user/plexmedia/tv:/tv
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=vlan-downloads"
      - "traefik.http.routers.bazarr.rule=Host(`subtitles.${DOMAIN}`)"
      - "traefik.http.routers.bazarr.tls=true"
      - "traefik.http.routers.bazarr.tls.certresolver=letsencrypt"
      - "traefik.http.services.bazarr.loadbalancer.server.port=32400"
  
  overseerr: #requests
    image: sctx/overseerr:latest
    container_name: overseerr
    depends_on:
      - traefik
      - plex
      - sonarr
      - radarr
    restart: unless-stopped
    networks:
      vlan-downloads:
        ipv4_address: 192.168.60.65
    ports:
      - "10000:10000" #web interface
    volumes:
      - /mnt/user/appdata/overseerr:/app/config
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=vlan-downloads"
      - "traefik.http.routers.overseerr.rule=Host(`request.${DOMAIN}`)"
      - "traefik.http.routers.overseerr.tls=true"
      - "traefik.http.routers.overseerr.tls.certresolver=letsencrypt"
      - "traefik.http.services.overseerr.loadbalancer.server.port=10000"


networks:
  vlan-private:
    external: true
  vlan-downloads:
    external: true
#done
