networks:
  vlan-private:
    driver: macvlan
    driver_opts:
      parent: br0.1
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1

  vlan-public:
    driver: macvlan
    driver_opts:
      parent: br0.20
    ipam:
      config:
        - subnet: 192.168.20.0/24
          gateway: 192.168.20.1

  vlan-iot:
    driver: macvlan
    driver_opts:
      parent: br0.40
    ipam:
      config:
        - subnet: 192.168.40.0/24
          gateway: 192.168.40.1

  vlan-downloads:
    driver: macvlan
    driver_opts:
      parent: br0.60
    ipam:
      config:
        - subnet: 192.168.60.0/24
          gateway: 192.168.60.1

  vlan-cameras:
    driver: macvlan
    driver_opts:
      parent: br0.70
    ipam:
      config:
        - subnet: 192.168.70.0/24
          gateway: 192.168.70.1
