version: '3'

services:
  network-init:
    image: alpine:latest
    command: "true"
    networks:
      - vlan-private
    deploy:
      restart_policy:
        condition: none
    profiles:
      - donotstart  # This prevents it from actually starting

networks:
  vlan-private:    # alias network
    external: true
    name: br0

  vlan-public:
    name: vlan-public
    driver: macvlan
    driver_opts:
      parent: br0.20
    ipam:
      config:
        - subnet: 192.168.20.0/24
          gateway: 192.168.20.1

  vlan-iot:
    name: vlan-iot
    driver: macvlan
    driver_opts:
      parent: br0.40
    ipam:
      config:
        - subnet: 192.168.40.0/24
          gateway: 192.168.40.1

  vlan-downloads:
    name: vlan-downloads
    driver: macvlan
    driver_opts:
      parent: br0.60
    ipam:
      config:
        - subnet: 192.168.60.0/24
          gateway: 192.168.60.1

  vlan-cameras:
    name: vlan-cameras
    driver: macvlan
    driver_opts:
      parent: br0.70
    ipam:
      config:
        - subnet: 192.168.70.0/24
          gateway: 192.168.70.1
