version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    networks:
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/portainer/data:/data
    environment:
      - TZ=${TZ}
      - PORTAINER_ADMIN_PASSWORD_FILE=/run/secrets/portainer_pass
    secrets:
      - portainer_pass
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  default:
    external: true
    name: vlan-default

secrets:
  portainer_pass:
    file: ./config/portainer/portainer-pass
