version: '3'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    networks:
      vlan-private:
        ipv4_address: 192.168.1.2
      vlan-iot:
        ipv4_address: 192.168.40.2
      vlan-downloads:
        ipv4_address: 192.168.60.2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../config/traefik:/etc/traefik
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_DNS_API_TOKEN=${CF_API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.jamespate.net`)"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    restart: unless-stopped

providers:
  docker:
    network: vlan-downloads
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"

networks:
  vlan-private:
    external: true 
  vlan-downloads:
    external: true
