version: '3'

networks:
  private_net:
    external: true

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    networks:
      - private_net
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../config/portainer:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN}`)"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    networks:
      - private_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_SCHEDULE=0 0 4 * * * # Run at 4 AM
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=${NOTIFICATION_URL}
    labels:
      - "traefik.enable=false"
    restart: unless-stopped
